# Generated by Django 4.1 on 2022-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number_order", models.CharField(blank=True, max_length=256)),
                ("price_usd", models.IntegerField(blank=True)),
                ("delivery_date", models.DateField(blank=True)),
                ("price_rub", models.IntegerField(blank=True)),
            ],
        ),
    ]
