# Generated by Django 4.1 on 2022-08-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price_rub",
            field=models.FloatField(blank=True),
        ),
    ]
